from configs import server_ip_addr

url_host = 'http://' + server_ip_addr + '/TPK/'
url_login = url_host + 'Login/Login'
url_login_asset = url_host + 'BelongingsCheck/UserCheck'
url_case_stats = url_host + 'TPKD0401F/QueryGrid'
url_asset = url_host + 'TPKD0602R/QueryOthersGrid'
url_asset_print = url_host + 'TPKD0602R/PrintOthers'
url_todestroy_case_stats = url_host + 'TPKH0401F/QueryGrid'
url_ended_case_stats = url_host + 'TPKH0204F/QueryGrid'
url_cases_attributes = url_host + 'TPKD0403F/QueryGrid'
url_post_ended_request = url_host + 'TPKD0403F/SetEndSituIDMulti'
url_cancel_ended_request = url_host + 'TPKD0403F/SetUndoEndSituID'
url_topay_summary = url_host + 'TPKD0509F/QueryGrid'
url_detainable_list = url_host + 'TPKI0602F/QueryGrid'
url_case_details = url_host + 'TPKD0201F/QueryData'
url_bank_response_print = url_host + 'TPKD0221F/Print'
